#!/bin/sh
set -x
if which nosetests-3.6 1>/dev/null 2>&1; then
	testexec="nosetests-3.6"
else
	testexec="nosetests"
fi

case `pwd` in
	*/test/unittests)
		PYTHONPATH=../.. $testexec --with-coverage --cover-xml-file=coverage.xml -w . "$@"
		;;
	*/test)
		PYTHONPATH=.. $testexec --with-coverage --cover-xml-file=coverage.xml -w unittests "$@"
		;;
	*)
		PYTHONPATH=. $testexec --with-coverage --cover-xml-file=coverage.xml -w test/unittests "$@"
		;;
esac

coverage xml
pip install six

ls -la test/unittests
ls -la test
ls -la `pwd`


