#!/bin/sh
set -x
if which nosetests-3.6 1>/dev/null 2>&1; then
	testexec="nosetests-3.6"
else
	testexec="nosetests"
fi

case `pwd` in
	*/test/unittests)
		PYTHONPATH=../.. $testexec -l DEBUG --with-coverage --cover-xml --cover-xml-file=coverage.xml -w . "$@"
		;;
	*/test)
		PYTHONPATH=.. $testexec -l DEBUG --with-coverage --cover-xml --cover-xml-file=coverage.xml -w unittests "$@"
		;;
	*)
		PYTHONPATH=. $testexec -l DEBUG --with-coverage --cover-xml --cover-xml-file=coverage.xml -w test/unittests "$@"
		;;
esac


ls -lh test/unittests
ls -lh `pwd`
